version: "3.8"

services:
  server:
    build: server
    ports:
      - "8080:8080"
    networks:
      - integration-network
    depends_on:
      - db
    environment:
      - POSTGRES_DB=jwt_security
  db:
    image: postgres
    restart: always
   
    networks:
      - integration-network
    environment:
      - POSTGRES_DB=jwt_security
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    expose:
      - 5432
  client:
    build:
      context: client
    ports:
      - "3000:80"
    networks:
      - web
    depends_on:
      - server
networks:
  integration-network:
  web: